INSERT into jn_security(id, name, shortname, sec_id, primary_board_id, type_id, created_at, updated_at)
VALUES (nextval('security_id_seq'), 'AED_TDSTMS - СВОП AED/РУБ', 'AED_TDSTMS', 'AEDRUBTDSTMS', 'CNGD', '3', now(),
        now()),
       (nextval('security_id_seq'), 'AED_TODTOM - СВОП AED/РУБ', 'AED_TODTOM', 'AEDRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'AED/RUB_SPT - AED/РУБ', 'AEDRUB_SPT', 'AEDRUB_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'AED/RUB_TDS - AED/РУБ', 'AEDRUB_TDS', 'AEDRUB_TDS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'AED/RUB_TMS - AED/РУБ', 'AEDRUB_TMS', 'AEDRUB_TMS', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'AED/RUB_TOD - AED/РУБ', 'AEDRUB_TOD', 'AEDRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'AED/RUB_TOM - AED/РУБ', 'AEDRUB_TOM', 'AEDRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'AED_TOMSPT - СВОП AED/РУБ', 'AED_TOMSPT', 'AEDRUB_TOM1D', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'AMDRUB_TDSTMS - AMD/РУБ', 'AMD_TDSTMS', 'AMDRUBTDSTMS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'AMD_TODTOM - СВОП AMD/РУБ', 'AMD_TODTOM', 'AMDRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'AMD/RUB_TDS - AMD/РУБ', 'AMDRUB_TDS', 'AMDRUB_TDS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'AMD/RUB_TMS - AMD/РУБ', 'AMDRUB_TMS', 'AMDRUB_TMS', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'AMD/RUB_TOD - AMD/РУБ', 'AMDRUB_TOD', 'AMDRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'AMD/RUB_TOM - AMD/РУБ', 'AMDRUB_TOM', 'AMDRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'BYNRUB_TDSTMS - BYN/РУБ', 'BYN_TDSTMS', 'BYNRUBTDSTMS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'BYN_TODTOM - СВОП BYN/РУБ', 'BYN_TODTOM', 'BYNRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'BYN/RUB_TDS - BYN/РУБ', 'BYNRUB_TDS', 'BYNRUB_TDS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'BYN/RUB_TMS - BYN/РУБ', 'BYNRUB_TMS', 'BYNRUB_TMS', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'BYN/RUB_TOD - BYN/РУБ', 'BYNRUB_TOD', 'BYNRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'BYN/RUB_TOM - BYN/РУБ', 'BYNRUB_TOM', 'BYNRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'CHFRUB_TDSTMS - CHF/РУБ', 'CHF_TDSTMS', 'CHFRUBTDSTMS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'CHF_TODTOM - СВОП CHF/РУБ', 'CHF_TODTOM', 'CHFRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'CHF/RUB_SPT - CHF/РУБ', 'CHFRUB_SPT', 'CHFRUB_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'CHF/RUB_TDS - CHF/РУБ', 'CHFRUB_TDS', 'CHFRUB_TDS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'CHF/RUB_TMS - CHF/РУБ', 'CHFRUB_TMS', 'CHFRUB_TMS', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'CHF/RUB_TOD - CHF/РУБ', 'CHFRUB_TOD', 'CHFRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'CHF/RUB_TOM - CHF/РУБ', 'CHFRUB_TOM', 'CHFRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'CHF_TOMSPT - СВОП CHF/РУБ', 'CHF_TOMSPT', 'CHFRUB_TOM1D', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'CNY/RUB_TOD - CNY/РУБ', 'CNYRUB_TOD', 'CNY000000TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'CNYRUB_TDSTMS - CNY/РУБ', 'CNY_TDSTMS', 'CNYRUBTDSTMS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'CNY_TODTOM - СВОП CNY/РУБ', 'CNY_TODTOM', 'CNYRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'CNY/RUB_SPT - CNY/РУБ', 'CNYRUB_SPT', 'CNYRUB_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'CNY/RUB_TDS - CNY/РУБ', 'CNYRUB_TDS', 'CNYRUB_TDS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'CNY/RUB_TMS - CNY/РУБ', 'CNYRUB_TMS', 'CNYRUB_TMS', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'CNY/RUB_TOM - CNY/РУБ', 'CNYRUB_TOM', 'CNYRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'CNY_TOMSPT СВОП CNY/РУБ', 'CNY_TOMSPT', 'CNYRUB_TOM1D', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'EUR_TODTOM - СВОП EUR/РУБ', 'EUR_TODTOM', 'EUR000TODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'EURRUB_TDSTMS - EUR/РУБ', 'EUR_TDSTMS', 'EURRUBTDSTMS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'EURRUB_SPT - EUR/РУБ', 'EURRUB_SPT', 'EURRUB_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'EUR/RUB_TDB - EUR/РУБ', 'EURRUB_TDB', 'EURRUB_TDB', 'SDBP', '3', now(), now()),
       (nextval('security_id_seq'), 'EURRUB_TDS - EUR/РУБ', 'EURRUB_TDS', 'EURRUB_TDS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'EUR/RUB_TMB - EUR/РУБ', 'EURRUB_TMB', 'EURRUB_TMB', 'SDBP', '3', now(), now()),
       (nextval('security_id_seq'), 'EURRUB_TMS - EUR/РУБ', 'EURRUB_TMS', 'EURRUB_TMS', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'EUR_TODSPT СВОП EUR/РУБ', 'EUR_TODSPT', 'EURRUB_TOD1D', 'AUCB', '3', now(), now()),
       (nextval('security_id_seq'), 'EUR_TOMSPT СВОП EUR/РУБ', 'EUR_TOMSPT', 'EURRUB_TOM1D', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'EUR/USD_TOD', 'EURUSD_TOD', 'EURUSD000TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'EUR/USD_TOM', 'EURUSD_TOM', 'EURUSD000TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'EUR/USD_TODTOM', 'EURUSDTDTM', 'EURUSDTODTOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'EUR/USD_SPT - EUR/USD', 'EURUSD_SPT', 'EURUSD_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'EUR/USD_TOMSPT - СВОП EUR/USD', 'EURUSDTMSP', 'EURUSD_TOM1D', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'EURRUB_TOD - EUR/РУБ', 'EURRUB_TOD', 'EUR_RUB__TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'EURRUB_TOM - EUR/РУБ', 'EURRUB_TOM', 'EUR_RUB__TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'GBPRUB_TDSTMS - GBP/РУБ', 'GBP_TDSTMS', 'GBPRUBTDSTMS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'GBP_TODTOM - СВОП GBP/РУБ', 'GBP_TODTOM', 'GBPRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'GBP/RUB_SPT - GBP/РУБ', 'GBPRUB_SPT', 'GBPRUB_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'GBP/RUB_TDS - GBP/РУБ', 'GBPRUB_TDS', 'GBPRUB_TDS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'GBP/RUB_TMS - GBP/РУБ', 'GBPRUB_TMS', 'GBPRUB_TMS', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'GBP/RUB_TOD - GBP/РУБ', 'GBPRUB_TOD', 'GBPRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'GBP/RUB_TOM - GBP/РУБ', 'GBPRUB_TOM', 'GBPRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'GBP_TOMSPT - СВОП GBP/РУБ', 'GBP_TOMSPT', 'GBPRUB_TOM1D', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'GBP/USD_TODTOM - СВОП GBP/USD', 'GBPUSDTDTM', 'GBPUSDTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'GBP/USD_SPT - GBP/USD', 'GBPUSD_SPT', 'GBPUSD_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'GBP/USD_TOD - GBP/USD', 'GBPUSD_TOD', 'GBPUSD_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'GBP/USD_TOM - GBP/USD', 'GBPUSD_TOM', 'GBPUSD_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'GBP/USD_TOMSPT - СВОП GBP/USD', 'GBPUSDTMSP', 'GBPUSD_TOM1D', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'HKDRUB_TDSTMS - HKD/РУБ', 'HKD_TDSTMS', 'HKDRUBTDSTMS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'HKD_TODTOM - СВОП HKD/РУБ', 'HKD_TODTOM', 'HKDRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'HKD/RUB_TDS - HKD/РУБ', 'HKDRUB_TDS', 'HKDRUB_TDS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'HKD/RUB_TMS - HKD/РУБ', 'HKDRUB_TMS', 'HKDRUB_TMS', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'HKD/RUB_TOD - HKD/РУБ', 'HKDRUB_TOD', 'HKDRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'HKD/RUB_TOM - HKD/РУБ', 'HKDRUB_TOM', 'HKDRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'JPYRUB_TDSTMS - JPY/РУБ', 'JPY_TDSTMS', 'JPYRUBTDSTMS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'JPY_TODTOM', 'JPY_TODTOM', 'JPYRUBTODTOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'JPY/RUB_SPT - JPY/РУБ', 'JPYRUB_SPT', 'JPYRUB_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'JPY/RUB_TDS - JPY/РУБ', 'JPYRUB_TDS', 'JPYRUB_TDS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'JPY/RUB_TMS - JPY/РУБ', 'JPYRUB_TMS', 'JPYRUB_TMS', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'JPY/RUB_TOD - JPY/RUB', 'JPYRUB_TOD', 'JPYRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'JPY/RUB_TOM - JPY/RUB', 'JPYRUB_TOM', 'JPYRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'JPY_TOMSPT - СВОП JPY/РУБ', 'JPY_TOMSPT', 'JPYRUB_TOM1D', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'KGS_TODTOM - СВОП KGS/РУБ', 'KGS_TODTOM', 'KGSRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'KGS/RUB_TOD - KGS/РУБ', 'KGSRUB_TOD', 'KGSRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'KGS/RUB_TOM - KGS/РУБ', 'KGSRUB_TOM', 'KGSRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'KZTRUB_TDSTMS - KZT/РУБ', 'KZT_TDSTMS', 'KZTRUBTDSTMS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'KZT/RUB_TODTOM - СВОП KZT/RUB', 'KZT_TODTOM', 'KZTRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'KZT/RUB_SPT - KZT/RUB', 'KZTRUB_SPT', 'KZTRUB_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'KZT/RUB_TDS - KZT/РУБ', 'KZTRUB_TDS', 'KZTRUB_TDS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'KZT/RUB_TMS - KZT/РУБ', 'KZTRUB_TMS', 'KZTRUB_TMS', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'KZT/RUB_TOD - KZT/RUB', 'KZTRUB_TOD', 'KZTRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'KZT/RUB_TOM - KZT/RUB', 'KZTRUB_TOM', 'KZTRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'KZT/RUB_TOMSPT - СВОП KZT/RUB', 'KZT_TOMSPT', 'KZTRUB_TOM1D', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'PLD_TODTOM - СВОП PLD/РУБ', 'PLD_TODTOM', 'PLDRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'PLD/RUB_LTV - PLD/РУБ', 'PLDRUB_LTV', 'PLDRUB_FWD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'PLD/RUB_SPT - PLD/РУБ', 'PLDRUB_SPT', 'PLDRUB_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'PLD/RUB_TOD - PLD/РУБ', 'PLDRUB_TOD', 'PLDRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'PLD/RUB_TOM - PLD/РУБ', 'PLDRUB_TOM', 'PLDRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'PLD_TOMSPT - СВОП PLD/РУБ', 'PLD_TOMSPT', 'PLDRUB_TOM1D', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'TOM_1M СВОП PLD/РУБ', 'PLD_TOM1M', 'PLDRUB_TOM1M', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'TOM_1W СВОП PLD/РУБ', 'PLD_TOM1W', 'PLDRUB_TOM1W', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'TOM_6M СВОП PLD/РУБ', 'PLD_TOM6M', 'PLDRUB_TOM6M', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'PLT_TODTOM - СВОП PLT/РУБ', 'PLT_TODTOM', 'PLTRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'PLT/RUB_LTV - PLT/РУБ', 'PLTRUB_LTV', 'PLTRUB_FWD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'PLT/RUB_SPT - PLT/РУБ', 'PLTRUB_SPT', 'PLTRUB_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'PLT/RUB_TOD - PLT/РУБ', 'PLTRUB_TOD', 'PLTRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'PLT/RUB_TOM - PLT/РУБ', 'PLTRUB_TOM', 'PLTRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'PLT_TOMSPT - СВОП PLT/РУБ', 'PLT_TOMSPT', 'PLTRUB_TOM1D', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'TOM_1M СВОП PLT/РУБ', 'PLT_TOM1M', 'PLTRUB_TOM1M', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'TOM_1W СВОП PLT/РУБ', 'PLT_TOM1W', 'PLTRUB_TOM1W', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'TOM_6M СВОП PLT/РУБ', 'PLT_TOM6M', 'PLTRUB_TOM6M', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'RUB/KZT_TOM - РУБ/KZT', 'RUBKZT_TOM', 'RUBKZT_TOM', 'OTCT', '3', now(), now()),
       (nextval('security_id_seq'), 'TJS_TODTOM - СВОП TJS/РУБ', 'TJS_TODTOM', 'TJSRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'TJS/RUB_TOD - TJS/РУБ', 'TJSRUB_TOD', 'TJSRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'TJS/RUB_TOM - TJS/РУБ', 'TJSRUB_TOM', 'TJSRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'TRYRUB_TDSTMS - TRY/РУБ', 'TRY_TDSTMS', 'TRYRUBTDSTMS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'TRY_TODTOM - СВОП TRY/РУБ', 'TRY_TODTOM', 'TRYRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'TRY/RUB_TDS - TRY/РУБ', 'TRYRUB_TDS', 'TRYRUB_TDS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'TRY/RUB_TMS - TRY/РУБ', 'TRYRUB_TMS', 'TRYRUB_TMS', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'TRY/RUB_TOD - TRY/РУБ', 'TRYRUB_TOD', 'TRYRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'TRY/RUB_TOM - TRY/РУБ', 'TRYRUB_TOM', 'TRYRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'UAHRUB_TOD - UAH/РУБ', 'UAHRUB_TOD', 'UAH000000TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USDRUB_TOD - USD/РУБ', 'USDRUB_TOD', 'USD000000TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD_TODTOM - СВОП USD/РУБ', 'USD_TODTOM', 'USD000TODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USDRUB_TOM - USD/РУБ', 'USDRUB_TOM', 'USD000UTSTOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/AED_TODTOM - СВОП USD/AED', 'USDAEDTDTM', 'USDAEDTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USD/AED_SPT - USD/AED', 'USDAED_SPT', 'USDAED_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/AED_TOD - USD/AED', 'USDAED_TOD', 'USDAED_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/AED_TOM - USD/AED', 'USDAED_TOM', 'USDAED_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/AED_TOMSPT - USD/AED', 'USDAEDTMSP', 'USDAED_TOM1D', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USD/AMD_TODTOM - СВОП USD/AMD', 'USDAMDTDTM', 'USDAMDTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USD/AMD_TOD - USD/AMD', 'USDAMD_TOD', 'USDAMD_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/AMD_TOM - USD/AMD', 'USDAMD_TOM', 'USDAMD_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/CHF_TODTOM - СВОП USD/CHF', 'USDCHFTDTM', 'USDCHFTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USD/CHF_SPT - USD/CHF', 'USDCHF_SPT', 'USDCHF_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/CHF_TOD - USD/CHF', 'USDCHF_TOD', 'USDCHF_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/CHF_TOM - USD/CHF', 'USDCHF_TOM', 'USDCHF_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/CHF_TOMSPT - СВОП USD/CHF', 'USDCHFTMSP', 'USDCHF_TOM1D', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USD/CNY_TODTOM - СВОП USD/CNY', 'USDCNYTDTM', 'USDCNYTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USD/CNY_SPT - USD/CNY', 'USDCNY_SPT', 'USDCNY_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/CNY_TOD - USD/CNY', 'USDCNY_TOD', 'USDCNY_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/CNY_TOM - USD/CNY', 'USDCNY_TOM', 'USDCNY_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/CNY_TOMSPT - СВОП USD/CNY', 'USDCNYTMSP', 'USDCNY_TOM1D', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USD/HKD_TODTOM - СВОП USD/HKD', 'USDHKDTDTM', 'USDHKDTODTOM', 'CNGD', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USD/HKD_TOD - USD/HKD', 'USDHKD_TOD', 'USDHKD_TOD', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/HKD_TOM - USD/HKD', 'USDHKD_TOM', 'USDHKD_TOM', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/JPY_TODTOM - СВОП', 'USDJPYTDTM', 'USDJPYTODTOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/JPY_SPT - USD/JPY', 'USDJPY_SPT', 'USDJPY_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/JPY_TOD - USD/JPY', 'USDJPY_TOD', 'USDJPY_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/JPY_TOM - USD/JPY', 'USDJPY_TOM', 'USDJPY_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/JPY_TOMSPT - СВОП USD/JPY', 'USDJPYTMSP', 'USDJPY_TOM1D', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USD/KGS_TODTOM - СВОП USD/KGS', 'USDKGSTDTM', 'USDKGSTODTOM', 'CNGD', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USD/KGS_TOD - USD/KGS', 'USDKGS_TOD', 'USDKGS_TOD', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/KGS_TOM - USD/KGS', 'USDKGS_TOM', 'USDKGS_TOM', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/KZT_TODTOM - СВОП USD/KZT', 'USDKZTTDTM', 'USDKZTTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USD/KZT_SPT - USD/KZT', 'USDKZT_SPT', 'USDKZT_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/KZT_TOD - USD/KZT', 'USDKZT_TOD', 'USDKZT_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/KZT_TOM - USD/KZT', 'USDKZT_TOM', 'USDKZT_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/KZT_TOMSPT - СВОП USD/KZT', 'USDKZTTMSP', 'USDKZT_TOM1D', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USDRUB_TDSTMS - USD/РУБ', 'USD_TDSTMS', 'USDRUBTDSTMS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'Дискретный аукцион USD/РУБ', 'USDRUB_DIS', 'USDRUB_DIS', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USDRUB_SPT - USD/РУБ', 'USDRUB_SPT', 'USDRUB_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/RUB_TDB - USD/РУБ', 'USDRUB_TDB', 'USDRUB_TDB', 'SDBP', '3', now(), now()),
       (nextval('security_id_seq'), 'USDRUB_TDS - USD/РУБ', 'USDRUB_TDS', 'USDRUB_TDS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/RUB_TMB - USD/РУБ', 'USDRUB_TMB', 'USDRUB_TMB', 'SDBP', '3', now(), now()),
       (nextval('security_id_seq'), 'USDRUB_TMS - USD/РУБ', 'USDRUB_TMS', 'USDRUB_TMS', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD_TODSPT СВОП USD/РУБ', 'USD_TODSPT', 'USDRUB_TOD1D', 'AUCB', '3', now(), now()),
       (nextval('security_id_seq'), 'USD_TOMSPT СВОП USD/РУБ', 'USD_TOMSPT', 'USDRUB_TOM1D', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/TJS_TODTOM - СВОП USD/TJS', 'USDTJSTDTM', 'USDTJSTODTOM', 'CNGD', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USD/TJS_TOD - USD/TJS', 'USDTJS_TOD', 'USDTJS_TOD', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/TJS_TOM - USD/TJS', 'USDTJS_TOM', 'USDTJS_TOM', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/TRY_TODTOM - СВОП USD/TRY', 'USDTRYTDTM', 'USDTRYTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USD/TRY_SPT - USD/TRY', 'USDTRY_SPT', 'USDTRY_SPT', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/TRY_TOD - USD/TRY', 'USDTRY_TOD', 'USDTRY_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/TRY_TOM - USD/TRY', 'USDTRY_TOM', 'USDTRY_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/TRY_TOMSPT - СВОП USD/TRY', 'USDTRYTMSP', 'USDTRY_TOM1D', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USD/ZAR_TODTOM - СВОП USD/ZAR', 'USDZARTDTM', 'USDZARTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USD/ZAR_TOD - USD/ZAR', 'USDZAR_TOD', 'USDZAR_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USD/ZAR_TOM - USD/ZAR', 'USDZAR_TOM', 'USDZAR_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'UZS_TODTOM - СВОП UZS/РУБ', 'UZS_TODTOM', 'UZSRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'UZS/RUB_TOD - UZS/РУБ', 'UZSRUB_TOD', 'UZSRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'UZS/RUB_TOM - UZS/РУБ', 'UZSRUB_TOM', 'UZSRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'ZARRUB_TDSTMS - ZAR/РУБ', 'ZAR_TDSTMS', 'ZARRUBTDSTMS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'ZAR_TODTOM - СВОП ZAR/РУБ', 'ZAR_TODTOM', 'ZARRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'ZAR/RUB_TDS - ZAR/РУБ', 'ZARRUB_TDS', 'ZARRUB_TDS', 'CNGD', '3', now(), now()),
       (nextval('security_id_seq'), 'ZAR/RUB_TMS - ZAR/РУБ', 'ZARRUB_TMS', 'ZARRUB_TMS', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'ZAR/RUB_TOD - ZAR/РУБ', 'ZARRUB_TOD', 'ZARRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'ZAR/RUB_TOM - ZAR/РУБ', 'ZARRUB_TOM', 'ZARRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'BKT/RUB_TOM - BKT/РУБ', 'BKTRUB_TOM', 'BKTRUB000TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'BYR_TODTOM - СВОП BYR/РУБ', 'BYR_TODTOM', 'BYRRUBTODTOM', 'CETS', '3', now(),
        now()),
       (nextval('security_id_seq'), 'BYR/RUB_TOD - BYR/РУБ', 'BYRRUB_TOD', 'BYRRUB_TOD', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'BYR/RUB_TOM - BYR/РУБ', 'BYRRUB_TOM', 'BYRRUB_TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'CNYRUB_WAPV - CNY/РУБ', 'CNYRUBWAPV', 'CNYRUB_WAPV', 'WAPS', '3', now(), now()),
       (nextval('security_id_seq'), 'EURRUB_NYH - EUR/РУБ', 'EURRUB_NYH', 'EURRUB_NYH', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'TOM_1M NYH СВОП EUR/РУБ', 'EUR_NYH1M', 'EURRUB_NYH1M', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'TOM_2M NYH СВОП EUR/РУБ', 'EUR_NYH2M', 'EURRUB_NYH2M', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'TOM_3M NYH СВОП EUR/РУБ', 'EUR_NYH3M', 'EURRUB_NYH3M', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'KZTRUB_TOD - KZT/РУБ', 'KZTRUB_TOD', 'KZT000000TOM', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'USDEUR/RUB - Бивалютная корзина', 'USDEUR_BKT', 'USDEURBASKET', 'None', '3', now(),
        now()),
       (nextval('security_id_seq'), 'USDRUB_NYH - USD/РУБ', 'USDRUB_NYH', 'USDRUB_NYH', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'TOM_1M NYH СВОП USD/РУБ', 'USD_NYH1M', 'USDRUB_NYH1M', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'TOM_2M NYH СВОП USD/РУБ', 'USD_NYH2M', 'USDRUB_NYH2M', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'TOM_3M NYH СВОП USD/РУБ', 'USD_NYH3M', 'USDRUB_NYH3M', 'CETS', '3', now(), now()),
       (nextval('security_id_seq'), 'Балансировка риска USD_RUB', 'USDRUB_RSK', 'USDRUB_RSK', 'RFUD', '3', now(),
        now());
